from vpython import*
from time import*
floor=box(pos=vector(0,-5,0),color=color.red,length=10,height=.1,width=10)
ceiling=box(pos=vector(0,5,0),color=color.blue,length=10,height=.1,width=10)
backwall=box(pos=vector(0,0,-5),color=color.green,length=10,height=10,width=.1)
leftwall=box(pos=vector(-5,0,0),color=color.white,length=.1,width=10,height=10)
rightwall=box(pos=vector(0,-5,0),color=color.white,length=.1,width=10,height=10)

while True:
    pass
